language: node_js
os:
    - linux
node_js:
    - "stable"
    - "lts/*"
sudo: false
env:
  - NO_SANDBOX=true

script:
  - npm run lint
  - npm run tslint
  - npm run markdown-lint
  - travis_retry npm test

cache:
  directories:
    - node_modules
