language: node_js
os:
    - linux
node_js:
    - "stable"
    - "lts/*"
sudo: false
env:
  - NO_SANDBOX=true

addons:
  sonarcloud:
    organization: "angrykoala-github"
    token:
      secure: ${SONAR_TOKEN}

script:
  - npm run lint
  - npm run tslint
  - npm run markdown-lint
  - sonar-scanner

cache:
  directories:
    - node_modules
