language: node_js
os:
    - linux
node_js:
    - "stable"
    - "lts/*"
    - "8.0.0"
sudo: false
env:
  - NO_SANDBOX=true

script:
  - travis_retry npm test
  - npm run lint

cache:
  directories:
    - node_modules
