name: Publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          npm install
      - name: publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMTOKEN}}
